atlas_localization_adapter:
  ros__parameters:
    use_sim_time: False

    input_odometry_topic: "odin1/odometry"
    input_cloud_topic: "odin1/cloud_slam"
    input_perception_cloud_topic: "cloud_registered"
    registered_scan_topic: "registered_scan"
    lidar_odometry_topic: "lidar_odometry"
    robot_base_odometry_topic: "odometry"
    base_yaw_joint_topic: "base_yaw_joint_publisher"
    odom_frame: "odom"
    base_frame: "base_footprint"
    robot_base_frame: "base_yaw"
    robot_base_odom_frame: "base_yaw_odom"
    lidar_frame: "odin1_base_link"
    perception_lidar_frame: "front_mid360"
    perception_enable: True
    perception_lidar_fusion_time_tolerance_sec: 0.15
    perception_lidar_fallback_timeout_sec: 0.20
    tf_lookup_timeout_sec: 0.05
